// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class CartItem
{
    public Guid ID { get; set; }

    public string LINEUserID { get; set; }

    public int Seq { get; set; }

    public Guid ProductID { get; set; }

    public int Quantity { get; set; }

    public DateTime CreatedDT { get; set; }

    public DateTime? ModifiedDT { get; set; }

    public virtual LINEUser LINEUser { get; set; }

    public virtual Product Product { get; set; }
}