// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class LINEUser
{
    public string ID { get; set; }

    public string DisplaName { get; set; }

    public string PictureUrl { get; set; }

    public string Language { get; set; }

    public string StatusMessage { get; set; }

    public DateTime? FollowDT { get; set; }

    public DateTime? UnfollowDT { get; set; }
}