// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class LINEPayRequest
{
    public Guid ID { get; set; }

    public string OrderNo { get; set; }

    public long? TransactionId { get; set; }

    public string RequestBody { get; set; }

    public string ResponseBody { get; set; }

    public DateTime CreatedDT { get; set; }
}