// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class OrderDetail
{
    public Guid ID { get; set; }

    public Guid OrderID { get; set; }

    public int Seq { get; set; }

    public Guid ProductID { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public DateTime CreatedDT { get; set; }

    public DateTime? ModifiedDT { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}