// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class Order
{
    public Guid ID { get; set; }

    public DateOnly OrderDate { get; set; }

    public int OrderSeq { get; set; }

    public string OrderNo { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaymentStatus { get; set; }

    public string LINEUserID { get; set; }

    public string Remark { get; set; }

    public DateTime CreatedDT { get; set; }

    public DateTime? ModifiedDT { get; set; }

    public virtual LINEUser LINEUser { get; set; }

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();
}