// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class Product
{
    public Guid ID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public decimal UnitPrice { get; set; }

    public Guid? MainImageFileID { get; set; }

    public DateTime CreatedDT { get; set; }

    public DateTime? ModifiedDT { get; set; }

    public virtual ICollection<CartItem> CartItem { get; set; } = new List<CartItem>();

    public virtual FileStorage MainImageFile { get; set; }

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();

    public virtual ICollection<ProductImage> ProductImage { get; set; } = new List<ProductImage>();
}