// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServer.Models.WebServerDB;

public partial class WebServerDBContext : DbContext
{
    public WebServerDBContext(DbContextOptions<WebServerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FileStorage> FileStorage { get; set; }

    public virtual DbSet<LINEUser> LINEUser { get; set; }

    public virtual DbSet<LINEUserMapping> LINEUserMapping { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductImage> ProductImage { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<FileStorage>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__FileStor__3214EC279A12C385");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Path)
                .IsRequired()
                .HasMaxLength(400);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LINEUser>(entity =>
        {
            entity.Property(e => e.ID).HasMaxLength(50);
            entity.Property(e => e.DisplaName).HasMaxLength(200);
            entity.Property(e => e.FollowDT).HasColumnType("datetime");
            entity.Property(e => e.Language).HasMaxLength(20);
            entity.Property(e => e.PictureUrl).HasMaxLength(500);
            entity.Property(e => e.StatusMessage).HasMaxLength(500);
            entity.Property(e => e.UnfollowDT).HasColumnType("datetime");
        });

        modelBuilder.Entity<LINEUserMapping>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEUser__3214EC2716D2EE52");

            entity.HasIndex(e => new { e.LINEUserID, e.UserID }, "UQ_LINEUserID_UserID").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.LINEUserID)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");

            entity.HasOne(d => d.LINEUser).WithMany(p => p.LINEUserMapping)
                .HasForeignKey(d => d.LINEUserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LINEUserM__LINEU__1DB06A4F");

            entity.HasOne(d => d.User).WithMany(p => p.LINEUserMapping)
                .HasForeignKey(d => d.UserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LINEUserM__UserI__1CBC4616");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Product__3214EC2744B26BB4");

            entity.HasIndex(e => e.ProductCode, "UQ__Product__2F4E024F7AF53008").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ProductDescription).HasMaxLength(500);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.MainImageFile).WithMany(p => p.Product)
                .HasForeignKey(d => d.MainImageFileID)
                .HasConstraintName("FK__Product__MainIma__0B91BA14");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__ProductI__3214EC27AFC460CD");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");

            entity.HasOne(d => d.File).WithMany(p => p.ProductImage)
                .HasForeignKey(d => d.FileID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__FileI__0F624AF8");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImage)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__Produ__0E6E26BF");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EmailNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LockoutEnd).HasColumnType("datetime");
            entity.Property(e => e.Mobile).HasMaxLength(100);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}