// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServer.Models.WebServerDB;

public partial class WebServerDBContext : DbContext
{
    public WebServerDBContext(DbContextOptions<WebServerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LINEUser> LINEUser { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<LINEUser>(entity =>
        {
            entity.Property(e => e.ID).HasMaxLength(50);
            entity.Property(e => e.DisplaName).HasMaxLength(200);
            entity.Property(e => e.FollowDT).HasColumnType("datetime");
            entity.Property(e => e.Language).HasMaxLength(20);
            entity.Property(e => e.PictureUrl).HasMaxLength(500);
            entity.Property(e => e.StatusMessage).HasMaxLength(500);
            entity.Property(e => e.UnfollowDT).HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EmailNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LockoutEnd).HasColumnType("datetime");
            entity.Property(e => e.Mobile).HasMaxLength(100);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}