// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServer.Models.WebServerDB;

public partial class WebServerDBContext : DbContext
{
    public WebServerDBContext(DbContextOptions<WebServerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CartItem> CartItem { get; set; }

    public virtual DbSet<FileStorage> FileStorage { get; set; }

    public virtual DbSet<LINEPayCapture> LINEPayCapture { get; set; }

    public virtual DbSet<LINEPayConfirm> LINEPayConfirm { get; set; }

    public virtual DbSet<LINEPayRefund> LINEPayRefund { get; set; }

    public virtual DbSet<LINEPayRequest> LINEPayRequest { get; set; }

    public virtual DbSet<LINEPayVoid> LINEPayVoid { get; set; }

    public virtual DbSet<LINEUser> LINEUser { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<OrderDetail> OrderDetail { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductImage> ProductImage { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CartItem__3214EC27D6B440FB");

            entity.HasIndex(e => new { e.LINEUserID, e.ProductID }, "UQ__CartItem__B7F18F60593AC271").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.LINEUserID)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");

            entity.HasOne(d => d.LINEUser).WithMany(p => p.CartItem)
                .HasForeignKey(d => d.LINEUserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItem__LINEUs__55F4C372");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItem)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItem__Produc__56E8E7AB");
        });

        modelBuilder.Entity<FileStorage>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__FileStor__3214EC279A12C385");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Path)
                .IsRequired()
                .HasMaxLength(400);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<LINEPayCapture>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEPayC__3214EC2736F08652");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RequestBody).IsRequired();
        });

        modelBuilder.Entity<LINEPayConfirm>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEPayC__3214EC27CE687755");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RequestBody).IsRequired();
        });

        modelBuilder.Entity<LINEPayRefund>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEPayR__3214EC272E0C756D");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RequestBody).IsRequired();
        });

        modelBuilder.Entity<LINEPayRequest>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEPayR__3214EC27DB16F2CB");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RequestBody).IsRequired();
        });

        modelBuilder.Entity<LINEPayVoid>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LINEPayV__3214EC2777DC5E74");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<LINEUser>(entity =>
        {
            entity.Property(e => e.ID).HasMaxLength(50);
            entity.Property(e => e.DisplaName).HasMaxLength(200);
            entity.Property(e => e.FollowDT).HasColumnType("datetime");
            entity.Property(e => e.Language).HasMaxLength(20);
            entity.Property(e => e.PictureUrl).HasMaxLength(500);
            entity.Property(e => e.StatusMessage).HasMaxLength(500);
            entity.Property(e => e.UnfollowDT).HasColumnType("datetime");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Order__3214EC270C9DF247");

            entity.HasIndex(e => e.OrderNo, "IX_Order").IsUnique();

            entity.HasIndex(e => new { e.OrderDate, e.OrderSeq }, "UQ__Order__288168EEA3B4DACF").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.LINEUserID)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.LINEUser).WithMany(p => p.Order)
                .HasForeignKey(d => d.LINEUserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Order__LINEUserI__395884C4");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__OrderDet__3214EC27C81671FE");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetail)
                .HasForeignKey(d => d.OrderID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Order__3C34F16F");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetail)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__3D2915A8");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Product__3214EC2744B26BB4");

            entity.HasIndex(e => e.ProductCode, "UQ__Product__2F4E024F7AF53008").IsUnique();

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.ProductCode)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ProductDescription).HasMaxLength(500);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.MainImageFile).WithMany(p => p.Product)
                .HasForeignKey(d => d.MainImageFileID)
                .HasConstraintName("FK__Product__MainIma__0B91BA14");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__ProductI__3214EC27AFC460CD");

            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");

            entity.HasOne(d => d.File).WithMany(p => p.ProductImage)
                .HasForeignKey(d => d.FileID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__FileI__0F624AF8");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImage)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__Produ__0E6E26BF");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.CreatedDT).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EmailNormalize)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LockoutEnd).HasColumnType("datetime");
            entity.Property(e => e.Mobile).HasMaxLength(100);
            entity.Property(e => e.ModifiedDT).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(256);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}